name: Generate Profile Visualizations

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate Multi-User 3D Contribution Map
        uses: ./.github/actions/3d-contrib-multi
        with:
          github_user_names: |
            SoxZz5
            SoxZz5-Zoop
            LucasGIFFARD
          github_tokens: |
            ${{ secrets.TOKEN_ACCOUNT1 }}
            ${{ secrets.TOKEN_ACCOUNT2 }}
            ${{ secrets.TOKEN_ACCOUNT3 }}
          output_dir: dist
          theme: night-rainbow

      - name: Generate Multi-User Trophies
        uses: ./.github/actions/trophies-multi
        with:
          github_user_names: |
            SoxZz5
            SoxZz5-Zoop
            LucasGIFFARD
          github_tokens: |
            ${{ secrets.TOKEN_ACCOUNT1 }}
            ${{ secrets.TOKEN_ACCOUNT2 }}
            ${{ secrets.TOKEN_ACCOUNT3 }}
          output: dist/github-trophies.svg
          theme: darkhub
          column: '4'

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
